swagger: '2.0'
info:
  description: >-
    An active cyber defense development framework enabling orchestration
    capabilities to be written once and deployed across WALKOFF-enabled
    orchestration tools. https://iadgov.github.io/WALKOFF/
  version: 0.1.2
  title: WALKOFF
  contact:
    email: walkoff@nsa.gov
  license:
    name: Creative-Commons
    url: 'http://creativecommons.org/licenses/by/4.0/'

tags:
  - name: Apps
    description: App Management Operations
  - name: Cases
    description: WALKOFF logging and case management operations
  - name: Subscriptions
    description: WALKOFF case subscription operations
  - name: Configuration
    description: System Configuration Operations
  - name: Devices
    description: Device Operations
  - name: Users
    description: User operations
  - name: Roles
    description: Role Operations
  - name: Metrics
    description: Metric Operations
  - name: Playbooks
    description: Playbook Operations
  - name: Workflows
    description: Workflow Operations
  - name: Events
    description: Event Operations
  - name: Scheduler
    description: Scheduler Operations
  - name: Widget
    description: Widget Operations
  - name: Widgets
    description: Multiple Widget Operations
  - name: Triggers
    description: Trigger Operations
  - name: System
    description: System Operations

schemes:
  - http
  - https

paths:
#  $ref: ./apps.yaml
#  $ref: ./cases.yaml
#  $ref: ./configuration.yaml
#  $ref: ./events.yaml
  $ref: ./metadata.yaml
#  $ref: ./metrics.yaml
#  $ref: ./playbooks.yaml
#  $ref: ./roles.yaml
#  $ref: ./scheduler.yaml
#  $ref: ./triggers.yaml
#  $ref: ./users.yaml
#  $ref: ./workflowresult.yaml

securityDefinitions:
  AuthenticationToken:
    type: apiKey
    name: Authentication-Token
    in: header

security:
  - AuthenticationToken: []

definitions:
    $ref: ./objects/objects.yaml
    $ref: ./objects/appdevice.yaml
    $ref: ./objects/cases.yaml
    $ref: ./objects/metrics.yaml
    $ref: ./objects/playbooks.yaml
    $ref: ./objects/roles.yaml
    $ref: ./objects/scheduler.yaml
    $ref: ./objects/triggers.yaml
    $ref: ./objects/users.yaml
    $ref: ./objects/workflowresult.yaml

