from os.path import join

api_path = join('.', 'server', 'api')
apps_path = join('.', 'apps')
case_db_path = join('data', 'events.db')
certificate_path = join('data', 'shortstop.public.pem')
config_path = join('.', 'data', 'walkoff.config')
data_path = join('.', 'data')
default_appdevice_export_path = join('.', 'data', 'appdevice.json')
default_case_export_path = join('.', 'data', 'cases.json')
device_db_path = join('data', 'devices.db')
db_path = join('data', 'walkoff.db')
interfaces_path = join('.', 'interfaces')
keywords_path = join('.', 'core', 'keywords')
logging_config_path = join('.', 'data', 'log', 'logging.json')
private_key_path = join('data', 'shortstop.private.pem')
workflows_path = join('.', 'workflows')
walkoff_schema_path = join(data_path, 'walkoff_schema.json')
function_api_path = join(data_path, 'functions.yaml')
client_path = join('.', 'client')
zmq_keys_path = join('.', '.certificates')
zmq_public_keys_path = join(zmq_keys_path, 'public_keys')
zmq_private_keys_path = join(zmq_keys_path, 'private_keys')
