__all__ = ['testBenchmarks',
           'testCaseDatabase',
           'testCaseServer',
           'testCaseSubscriptions',
           'testExecutionEvents',
           'testExecutionModes',
           'testExecutionRuntime',
           'testLoadWorkflow',
           'testServer',
           'testSimpleWorkflow',
           'testStreaming',
           'testTriggers',
           'testUsersAndRoles',
           'testAppsAndDevices',
           'testWorkflowManipulation']