"""removed some tables

Revision ID: 047bc4300282
Revises: 
Create Date: 2018-03-07 10:27:04.752708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047bc4300282'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result')
    op.drop_table('workflow')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('uid', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('result', sa.VARCHAR(), nullable=True),
    sa.Column('arguments', sa.VARCHAR(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=True),
    sa.Column('action_name', sa.VARCHAR(), nullable=True),
    sa.Column('app_name', sa.VARCHAR(), nullable=True),
    sa.Column('workflow_result_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_result_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
