"""Update resources and permissions structure

Revision ID: a92d6ad1d345
Revises: 
Create Date: 2017-12-15 11:59:59.856717

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a92d6ad1d345'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource',
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('modified_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('permission',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('resource_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('resource_permission')
    op.drop_table('roles_resources_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_resources_association',
                    sa.Column('resource_permission_id', sa.INTEGER(), nullable=True),
                    sa.Column('role_id', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(['resource_permission_id'], [u'resource_permission.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], )
                    )
    op.create_table('resource_permission',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('resource', sa.VARCHAR(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('resource')
                    )
    op.drop_table('permission')
    op.drop_table('resource')
    # ### end Alembic commands ###
