"""minor column name changes

Revision ID: f2bd05b25482
Revises: dd74ff55c643
Create Date: 2018-03-06 15:29:17.653749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import UUIDType


# revision identifiers, used by Alembic.
revision = 'f2bd05b25482'
down_revision = 'dd74ff55c643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("message") as batch_op:
        batch_op.alter_column("workflow_execution_uid", new_column_name="workflow_execution_id", type=UUIDType)

    with op.batch_alter_table("scheduled_workflow") as batch_op:
        batch_op.alter_column("uid", new_column_name="workflow_id", type=UUIDType, nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
