"""Added user column for workflow exec

Revision ID: 8bf64f228d24
Revises: de7dd1e1487c
Create Date: 2018-11-14 14:27:54.019978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf64f228d24'
down_revision = 'de7dd1e1487c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workflow', ['workflow_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('action_metric', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'app_metric', ['app_metric_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('action_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workflow_status', ['_workflow_status_id'], ['execution_id'], ondelete='CASCADE')

    with op.batch_alter_table('action_status_metric', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'action_metric', ['action_metric_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('argument', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'transform', ['transform_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'action', ['action_device_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'condition', ['condition_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'action', ['action_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workflow', ['workflow_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('condition', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'conditional_expression', ['conditional_expression_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('conditional_expression', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'conditional_expression', ['parent_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'action', ['action_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'app', ['app_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('encrypted_device_field', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'device', ['device_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('plaintext_device_field', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'device', ['device_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'action', ['action_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('saved_workflow', schema=None) as batch_op:
        batch_op.drop_column('accumulator')

    with op.batch_alter_table('transform', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'condition', ['condition_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'playbook', ['playbook_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('workflow_status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_status', schema=None) as batch_op:
        batch_op.drop_column('user')

    with op.batch_alter_table('workflow', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'playbook', ['playbook_id'], ['id'])

    with op.batch_alter_table('transform', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'condition', ['condition_id'], ['id'])

    with op.batch_alter_table('saved_workflow', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accumulator', sa.BLOB(), nullable=False))

    with op.batch_alter_table('position', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'action', ['action_id'], ['id'])

    with op.batch_alter_table('plaintext_device_field', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'device', ['device_id'], ['id'])

    with op.batch_alter_table('encrypted_device_field', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'device', ['device_id'], ['id'])

    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'app', ['app_id'], ['id'])

    with op.batch_alter_table('conditional_expression', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'conditional_expression', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'action', ['action_id'], ['id'])
        batch_op.create_foreign_key(None, 'branch', ['branch_id'], ['id'])

    with op.batch_alter_table('condition', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'conditional_expression', ['conditional_expression_id'], ['id'])

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workflow', ['workflow_id'], ['id'])

    with op.batch_alter_table('argument', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'transform', ['transform_id'], ['id'])
        batch_op.create_foreign_key(None, 'condition', ['condition_id'], ['id'])
        batch_op.create_foreign_key(None, 'action', ['action_device_id'], ['id'])
        batch_op.create_foreign_key(None, 'action', ['action_id'], ['id'])

    with op.batch_alter_table('action_status_metric', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'action_metric', ['action_metric_id'], ['id'])

    with op.batch_alter_table('action_status', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workflow_status', ['_workflow_status_id'], ['execution_id'])

    with op.batch_alter_table('action_metric', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'app_metric', ['app_metric_id'], ['id'])

    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'workflow', ['workflow_id'], ['id'])

    # ### end Alembic commands ###
