"""0.8.0

Revision ID: 8a602ed5ea63
Revises: f2bd05b25482
Create Date: 2018-04-16 16:37:06.148564

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '8a602ed5ea63'
down_revision = 'f2bd05b25482'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_messages',
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('message_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
                    )
    with op.batch_alter_table(u'scheduled_workflow', schema=None) as batch_op:
        batch_op.alter_column('workflow_id',
                              existing_type=sa.NUMERIC(precision=16),
                              type_=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
                              existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'scheduled_workflow', schema=None) as batch_op:
        batch_op.alter_column('workflow_id',
                              existing_type=sqlalchemy_utils.types.uuid.UUIDType(binary=False),
                              type_=sa.NUMERIC(precision=16),
                              existing_nullable=False)

    op.drop_table('role_messages')
    # ### end Alembic commands ###
