version: '3.5'
services:
  core_umpire:
    image: "127.0.0.1:5000/walkoff_core_umpire:latest"
#    command: python -m umpire.umpire --log-level=debug --disable-worker-autoheal --disable-worker-autoscale
    build:
      context: ./
      dockerfile: umpire/Dockerfile
    networks:
      - walkoff_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./apps:/app/apps
    deploy:
      placement:
        constraints: [node.role==manager]
    depends_on:
      - resource_redis
      - resource_registry
      - resource_minio
      - core_api
    secrets:
      - walkoff_encryption_key
      - walkoff_internal_key
      - walkoff_minio_access_key
      - walkoff_minio_secret_key
      - walkoff_redis_key
    configs:
      - common_env.yml

  core_api:
    image: "127.0.0.1:5000/walkoff_core_api:latest"
    build:
      context: ./
      dockerfile: ./api/Dockerfile
#    ports:
#      - '8080:8080'
    networks:
      - walkoff_network
#    stop_signal: SIGINT
#    stop_grace_period: 30s
    secrets:
      - walkoff_encryption_key
      - walkoff_internal_key
      - walkoff_mongo_key
      - walkoff_redis_key
      - walkoff_minio_access_key
      - walkoff_minio_secret_key
    configs:
      - common_env.yml
    depends_on:
      - resource_redis
      - resource_mongo
      - core_socketio
    volumes:
      - ./apps:/app/apps
      - ./api/client/dist:/app/api/client/dist
      - /var/run/docker.sock:/var/run/docker.sock

  core_socketio:
    image: "127.0.0.1:5000/walkoff_core_socketio:latest"
    build:
      context: ./
      dockerfile: ./socketio/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - walkoff_network
#    stop_signal: SIGINT
#    stop_grace_period: 30s
    secrets:
      # - walkoff_encryption_key
      - walkoff_internal_key
      # - walkoff_mongo_key
      # - walkoff_redis_key
    configs:
      - common_env.yml
    # volumes:
    #   - ./api/client/dist:/app/api/client/dist

  resource_nginx:
    image: 'bitnami/nginx:latest'
    networks:
      - walkoff_network
    ports:
      - '8080:8080'
#      - '8081:8081' # Uncomment for unsecure HTTP access to API Gateway
    volumes:
      - ./nginx/walkoff.conf:/opt/bitnami/nginx/conf/server_blocks/walkoff.conf:ro
      - ./nginx/cert.pem:/opt/bitnami/nginx/conf/cert.pem:ro
      - ./nginx/key.pem:/opt/bitnami/nginx/conf/key.pem:ro
    depends_on:
      - core_api
      - core_socketio

  core_worker:
    command: python -m worker.worker --log-level=debug
    image: "127.0.0.1:5000/walkoff_core_worker:latest"
    networks:
      - walkoff_network
    secrets:
      - walkoff_internal_key
      - walkoff_redis_key
    build:
      context: ./
      dockerfile: ./worker/Dockerfile
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none

  app_sdk:
    networks:
      - walkoff_network
    build:
      context: ./
      dockerfile: ./app_sdk/Dockerfile
    image: "127.0.0.1:5000/walkoff_app_sdk:latest"
    configs:
      - common_env.yml
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: none

configs:
  common_env.yml:
    file: ./data/config.yml

secrets:
  walkoff_encryption_key:
    external: true
  walkoff_internal_key:
    external: true
  walkoff_mongo_key:
    external: true
  walkoff_redis_key:
    external: true
  walkoff_minio_access_key:
    external: true
  walkoff_minio_secret_key:
    external: true

networks:
  walkoff_network:
    external: true
