# coding: utf-8

"""
    WALKOFF

    An active cyber defense development framework enabling orchestration capabilities to be written once and deployed across WALKOFF-enabled orchestration tools. https://nsacyber.github.io/WALKOFF/  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Contact: walkoff@nsa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import walkoff_client
from walkoff_client.api.roles_api import RolesApi  # noqa: E501
from walkoff_client.rest import ApiException


class TestRolesApi(unittest.TestCase):
    """RolesApi unit test stubs"""

    def setUp(self):
        self.api = walkoff_client.api.roles_api.RolesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_role(self):
        """Test case for create_role

        Create a role  # noqa: E501
        """
        pass

    def test_delete_role(self):
        """Test case for delete_role

        Delete a role  # noqa: E501
        """
        pass

    def test_read_all_roles(self):
        """Test case for read_all_roles

        Read all roles  # noqa: E501
        """
        pass

    def test_read_available_resource_actions(self):
        """Test case for read_available_resource_actions

        Read all available resource actions  # noqa: E501
        """
        pass

    def test_read_role(self):
        """Test case for read_role

        Read a role  # noqa: E501
        """
        pass

    def test_update_role(self):
        """Test case for update_role

        Update a role  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
