# coding: utf-8

"""
    WALKOFF

    An active cyber defense development framework enabling orchestration capabilities to be written once and deployed across WALKOFF-enabled orchestration tools. https://nsacyber.github.io/WALKOFF/  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Contact: walkoff@nsa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import walkoff_client
from walkoff_client.api.workflows_api import WorkflowsApi  # noqa: E501
from walkoff_client.rest import ApiException


class TestWorkflowsApi(unittest.TestCase):
    """WorkflowsApi unit test stubs"""

    def setUp(self):
        self.api = walkoff_client.api.workflows_api.WorkflowsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_workflow(self):
        """Test case for create_workflow

        Create a workflow  # noqa: E501
        """
        pass

    def test_delete_workflow(self):
        """Test case for delete_workflow

        Delete a workflow  # noqa: E501
        """
        pass

    def test_read_all_workflows(self):
        """Test case for read_all_workflows

        Read all workflows in playbook  # noqa: E501
        """
        pass

    def test_read_workflow(self):
        """Test case for read_workflow

        Read a workflow  # noqa: E501
        """
        pass

    def test_update_workflow(self):
        """Test case for update_workflow

        Update a workflow  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
