# coding: utf-8

"""
    WALKOFF

    An active cyber defense development framework enabling orchestration capabilities to be written once and deployed across WALKOFF-enabled orchestration tools. https://nsacyber.github.io/WALKOFF/  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Contact: walkoff@nsa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import walkoff_client
from walkoff_client.api.temp_internal_api import TempInternalApi  # noqa: E501
from walkoff_client.rest import ApiException


class TestTempInternalApi(unittest.TestCase):
    """TempInternalApi unit test stubs"""

    def setUp(self):
        self.api = walkoff_client.api.temp_internal_api.TempInternalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_update_workflow_status(self):
        """Test case for update_workflow_status

        Patch parts of a WorkflowStatusMessage object  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
