# coding: utf-8

"""
    WALKOFF

    An active cyber defense development framework enabling orchestration capabilities to be written once and deployed across WALKOFF-enabled orchestration tools. https://nsacyber.github.io/WALKOFF/  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Contact: walkoff@nsa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import walkoff_client
from walkoff_client.models.scheduler import Scheduler  # noqa: E501
from walkoff_client.rest import ApiException


class TestScheduler(unittest.TestCase):
    """Scheduler unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScheduler(self):
        """Test Scheduler"""
        # FIXME: construct object with mandatory attributes with example values
        # model = walkoff_client.models.scheduler.Scheduler()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
