# coding: utf-8

"""
    WALKOFF

    An active cyber defense development framework enabling orchestration capabilities to be written once and deployed across WALKOFF-enabled orchestration tools. https://nsacyber.github.io/WALKOFF/  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Contact: walkoff@nsa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import walkoff_client
from walkoff_client.api.global_variables_api import GlobalVariablesApi  # noqa: E501
from walkoff_client.rest import ApiException


class TestGlobalVariablesApi(unittest.TestCase):
    """GlobalVariablesApi unit test stubs"""

    def setUp(self):
        self.api = walkoff_client.api.global_variables_api.GlobalVariablesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_global(self):
        """Test case for create_global

        Add a global  # noqa: E501
        """
        pass

    def test_create_global_templates(self):
        """Test case for create_global_templates

        Add a global  # noqa: E501
        """
        pass

    def test_delete_global(self):
        """Test case for delete_global

        Remove a global  # noqa: E501
        """
        pass

    def test_delete_global_templates(self):
        """Test case for delete_global_templates

        Remove a global  # noqa: E501
        """
        pass

    def test_read_all_global_templates(self):
        """Test case for read_all_global_templates

        Get all global templates  # noqa: E501
        """
        pass

    def test_read_all_globals(self):
        """Test case for read_all_globals

        Get all globals  # noqa: E501
        """
        pass

    def test_read_global(self):
        """Test case for read_global

        Read a global  # noqa: E501
        """
        pass

    def test_read_global_templates(self):
        """Test case for read_global_templates

        Read a global template  # noqa: E501
        """
        pass

    def test_update_global(self):
        """Test case for update_global

        Update a global  # noqa: E501
        """
        pass

    def test_update_global_templates(self):
        """Test case for update_global_templates

        Update a global template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
