# coding: utf-8

"""
    WALKOFF

    An active cyber defense development framework enabling orchestration capabilities to be written once and deployed across WALKOFF-enabled orchestration tools. https://nsacyber.github.io/WALKOFF/  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Contact: walkoff@nsa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import walkoff_client
from walkoff_client.api.apps_api import AppsApi  # noqa: E501
from walkoff_client.rest import ApiException


class TestAppsApi(unittest.TestCase):
    """AppsApi unit test stubs"""

    def setUp(self):
        self.api = walkoff_client.api.apps_api.AppsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_app_api(self):
        """Test case for create_app_api

        Create app api  # noqa: E501
        """
        pass

    def test_delete_app_api(self):
        """Test case for delete_app_api

        Delete app api  # noqa: E501
        """
        pass

    def test_read_all_app_apis(self):
        """Test case for read_all_app_apis

        Get all app apis  # noqa: E501
        """
        pass

    def test_read_app_api(self):
        """Test case for read_app_api

        Get and app's api  # noqa: E501
        """
        pass

    def test_update_app_api(self):
        """Test case for update_app_api

        Replace app api  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
