# coding: utf-8

"""
    WALKOFF

    An active cyber defense development framework enabling orchestration capabilities to be written once and deployed across WALKOFF-enabled orchestration tools. https://nsacyber.github.io/WALKOFF/  # noqa: E501

    The version of the OpenAPI document: 0.9.1
    Contact: walkoff@nsa.gov
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import walkoff_client
from walkoff_client.api.system_api import SystemApi  # noqa: E501
from walkoff_client.rest import ApiException


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = walkoff_client.api.system_api.SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_all_app_names(self):
        """Test case for read_all_app_names

        Gets all apps  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
